### ISSUE TITLE
How to import caffe?

### ISSUE THREAD

**Issue by Savitha2018** [chenxinpeng/S2VT#20]
I got this error

Traceback (most recent call last):
  File "extract_RGB_feats.py", line 9, in <module>
    from cnn_util import *
  File "cnn_util.py", line 4, in <module>
    import caffe
  File "/content/drive/My Drive/S2VT/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/content/drive/My Drive/S2VT/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named _caffe

**Comment by abhirup2691** [comment]
use this before running the file
!apt install caffe-cuda
